### ISSUE TITLE
Retrieving for the scientific keyphrase datasets

### ISSUE THREAD

**Issue by wasiahmad** [boudinfl/ir-using-kg#1]
Hi, 

The documentation explains how to create indexing and perform an evaluation using the NTCIR dataset. Is it possible to give some pointer to do the same with the KP20k dataset?

**Comment by boudinfl** [comment]
Hi @wasiahmad,

KP20k is a benchmark dataset for keyphrase extraction/generation, i.e. a collection of documents paired with author-provided keyphrases. As such, it can not be used as a test collection for running IR experiments because there are no queries / relevance judgments. That being said, it is still possible (and quite easy) to index KP20k with anserini by 1/ downloading the dataset from Meng's repo (https://github.com/memray/seq2seq-keyphrase#data), 2/ (optional) converting the jsonl documents into TREC-formatted documents, and 3/ indexing the documents using anserini.

Best,

f.
